//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onboardingFinal.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class Sale
    {

        [ScaffoldColumn(false)]
        public int Id { get; set; }

        [Required(ErrorMessage = "Product Id is required")]
        public Nullable<int> ProductId { get; set; }
        [Required(ErrorMessage = "Customer Id is required")]
        public Nullable<int> CustomerId { get; set; }
        [Required(ErrorMessage = "Store Id is required")]
        public Nullable<int> StoreId { get; set; }
        [Required(ErrorMessage = "Date Id is required")]
        public string DateSold { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
